FROM debian:buster

# See https://github.com/SignalK/signalk-server/blob/master/raspberry_pi_installation.md#installing-signal-k

RUN apt-get update && apt-get -y install nodejs npm

RUN npm install -g npm@latest
RUN apt-get -y install libnss-mdns avahi-utils libavahi-compat-libdnssd-dev
RUN npm install -g --unsafe-perm signalk-server

CMD ["signalk-server", "--sample-nmea0183-data"]
